language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
   
before_install:
        - choco install python3 --params "/InstallDir:C:\\Python"
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
        - python -m pip install --upgrade pip
        - pip3 install -U pip
        - pip3 install -U pytest
        - pip3 install codecov

before_install:
    - SRC_DIR=$(pwd)

install: 
  #- pip3 install --upgrade pip  # all three OSes agree about 'pip3'
# 'python' points to Python 2.7 on macOS but points to Python 3.8 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
  #- pip3 install -r requirements.txt
  - cd ${SRC_DIR}
  - pip3 install -e .
  - pip3 install flake8
script:
        - cd guid_core
        - python3 -m pytest tests/
        - flake8 --max-complexity 12 .

notifications:
  email:
    recipients:
      - jeremygarcia937@gmail.com # a ajouter david et dipankar
    on_success: never # default: change
    on_failure: never # default: always

